meublog/urls.py
from django.urls import path
from . import views

app_name = 'meublog'

urlpatterns = [
    path('', views.ListarPostsView.as_view(), name='listar_posts'),
    path('<int:ano>/<int:mes>/<int:dia>/<slug:slug>/',
         views.DetalharPostView.as_view(), name='detalhe'),
    path('enviarpost/<int:pk>/',
         views.FormContatoView.as_view(),
         name='enviarpost'),
    path('comentar/<int:pk>/',
         views.ComentarioCreateView.as_view(),
         name='comentar_post'),
    path('cadastrousuario/',
         views.CadUsuarioView.as_view(),
         name="cadastrouser"),
    path('login/', views.LoginUsuarioView.as_view(),
         name='loginuser'),
    path('logout/', views.LogoutUsuarioView.as_view(),
         name='logoutuser'),
]

meusite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meublog.urls', namespace='meublog'))
]

admin.site.site_header = "Meu Blog"
admin.site.site_title = "Meu Blog - Ifro"
admin.site.index_title = "Gerenciar Meu Blog"

meublog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User


class PublicadosManager(models.Manager):
    def get_queryset(self):
        return super(PublicadosManager, self).get_queryset().filter(status='publicado')


class Post(models.Model):
    STATUS_CHOICES = (
        ('rascunho', 'Rascunho'),
        ('publicado', 'Publicado')
    )
    objects = models.Manager()
    publicados = PublicadosManager()

    titulo = models.CharField(max_length=250)
    slug = models.SlugField(max_length=100)
    corpo = models.TextField()
    autor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='meublog_posts')
    publicado = models.DateTimeField(default=timezone.now)
    criado = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=9, choices=STATUS_CHOICES, default='rascunho')

    class Meta:
        ordering = ('-publicado',)
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    def __str__(self):
        return self.titulo


class Comentario(models.Model):
    nome = models.CharField(max_length=50)
    email = models.EmailField()
    corpo = models.TextField()
    criado = models.DateTimeField(auto_now_add=True)
    atualizado = models.DateTimeField(auto_now=True)
    ativo = models.BooleanField(default=False)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Comentário"
        verbose_name_plural = "Comentários"

    def __str__(self):
        return f'Comentário de: {self.nome}'

meublog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.mail import EmailMessage

from meublog.models import Comentario


class EmailForm(forms.Form):
    nome = forms.CharField(max_length=100)
    email = forms.EmailField()
    destino = forms.EmailField()
    coments = forms.CharField(required=False,
                              widget=forms.Textarea)

    def enviar_email(self, meupost):
        nome = self.cleaned_data['nome']
        email = self.cleaned_data['email']
        destino = self.cleaned_data['destino']
        coments = self.cleaned_data['coments']

        conteudo = f'Leia o post: {meupost.titulo}\n' \
                   f'Comentários: {coments}'
        mail = EmailMessage(
            subject=f'{nome} recomenda ler o Post{meupost.titulo}',
            body=conteudo,
            from_email=email,
            to=[destino],
            headers={'Reply-To': email}
        )
        mail.send()

class ComentarioModelForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['nome', 'email', 'corpo']

    def salvarComentario(self, post):
        coment = self.save(commit=False)
        coment.post = post
        coment.nome = self.cleaned_data['nome']
        coment.email = self.cleaned_data['email']
        coment.corpo = self.cleaned_data['corpo']
        return coment.save()


class CadUsuarioForm(UserCreationForm):
    class Meta:
        model = User
        fields=['username','email']

meublog/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, FormView, CreateView

from meublog.forms import EmailForm, ComentarioModelForm, CadUsuarioForm
from meublog.models import Post, Comentario


class FormContatoView(FormView):
    template_name = 'meublog/post/enviarpost.html'
    form_class = EmailForm
    success_url = reverse_lazy('meublog:listar_posts')

    def get_post(self, id_post):
        try:
            return Post.publicados.get(pk=id_post)
        except Post.DoesNotExist:
            messages.error(self.request, 'Post não encontrado!')
            reverse_lazy('meublog:listar_posts')

    def get_context_data(self, **kwargs):
        context = super(FormContatoView, self).get_context_data(**kwargs)
        context['post'] = self.get_post(self.kwargs['pk'])
        return context

    def form_valid(self, form):
        meupost = self.get_context_data()['post']
        form.enviar_email(meupost)
        messages.success(self.request, f'Post {meupost.titulo} '
                                       f'enviado com sucesso.')
        return super(FormContatoView, self).form_valid(form)

    def form_invalid(self, form):
        meupost = self.get_context_data()['post']
        messages.error(self.request, f'Post {meupost.titulo} '
                                       f'não enviado.')
        return super(FormContatoView, self).form_invalid(form)



class ListarPostsView(ListView):
    queryset = Post.publicados.all()
    context_object_name = 'posts'
    paginate_by = 2
    template_name = "meublog/post/listarposts.html"


class DetalharPostView(DetailView):
    template_name = "meublog/post/detalharpost.html"
    model = Post

    def _get_coments(self, id_post):
        try:
            return Comentario.objects.filter(post_id=id_post,
                                             ativo=True)
        except Comentario.DoesNotExist:
            raise Exception

    def get_context_data(self, **kwargs):
        context = super(DetalharPostView, self).get_context_data(**kwargs)
        context['coments'] = self._get_coments(self.object.id)
        return context


class ComentarioCreateView(CreateView):
    template_name = "meublog/post/comentarios.html"
    form_class = ComentarioModelForm

    def _get_post(self, id_post):
        try:
            post = Post.publicados.get(pk=id_post)
            return post
        except Post.DoesNotExist:
            raise Exception

    def get_context_data(self, **kwargs):
        context = super(ComentarioCreateView, self).get_context_data(**kwargs)
        context['post'] = self._get_post(self.kwargs['pk'])
        return context

    def form_valid(self, form, **kwargs):
        post = self._get_post(self.kwargs['pk'])
        form.salvarComentario(post)
        return redirect('meublog:detalhe',
                        post.criado.year,
                        post.criado.month,
                        post.criado.day,
                        post.slug)


class CadUsuarioView(CreateView):
    template_name = 'meublog/usuarios/cadusuario.html'
    form_class = CadUsuarioForm #UserCreationForm
    success_url = reverse_lazy('meublog:loginuser')

    def form_valid(self, form, **kwargs):
        form.cleaned_data
        form.save()
        messages.success(self.request, "Usuário cadastrado")
        return super(CadUsuarioView, self).form_valid(form, **kwargs)

    def form_invalid(self, form):
        messages.error(self.request, "Não foi possível cadastrar")
        return super(CadUsuarioView, self).form_invalid(form)


class LoginUsuarioView(FormView):
    template_name = 'meublog/usuarios/login.html'
    model = User
    form_class = AuthenticationForm
    success_url = reverse_lazy('meublog:listar_posts')

    def form_valid(self, form):
        nome = form.cleaned_data['username']
        senha = form.cleaned_data['password']
        usuario = authenticate(self.request,
                               username=nome,
                               password=senha)
        if usuario is not None:
            login(self.request, usuario)
            return redirect('meublog:listar_posts')
        messages.error(self.request,
                       f"Usuário não existe")
        return redirect('meublog:loginuser')

class LogoutUsuarioView(LoginRequiredMixin, LogoutView):

    def get(self, request):
        logout(request)
        return redirect('meublog:listar_posts')

meublog/templates/meublog/post/comentarios.html
{% extends "meublog/base.html" %}

{% block titulo %}
    Comentário post {{ post.slug }}
{% endblock %}

{% block conteudo %}
{% if user.is_authenticated %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Salvar">
    </form>
{% else %}
    <h2 class="text-danger">Disponível apenas para
        usuários autenticados</h2>
    <a class="btn btn-primary"
       href="{% url 'meublog:listar_posts' %}">
        Voltar
    </a>
{% endif %}
{% endblock %}

meublog/templates/meublog/post/detalharpost.html
{% extends 'meublog/base.html' %}

{% block titulo %} {{ post.titulo }} {% endblock %}


{% block conteudo %}
    <h1>{{ post.titulo }}</h1>
    <p class="date">
        Publicado em {{ post.publicado }} por {{ post.autor }}
    </p>
    <p>
        {{ post.corpo|linebreaks }}
    </p>
    <br>
    <h4>
        <a href="{% url 'meublog:enviarpost' post.id %}">
            Enviar este post...
        </a> &nbsp;&nbsp;&nbsp;
        <a href="{% url 'meublog:comentar_post' post.id %}">
            Comentar este post...
        </a>
    </h4>
    <h2>Comentários</h2>
    {% for c in coments %}
        <p>Comentário de {{ c.nome }}<br>
            <b>{{ c.corpo }}</b>
        </p>
    {% endfor %}
{% endblock %}

meublog/templates/meublog/post/enviarpost.html
{% extends "meublog/base.html" %}

{% block titulo %}
   Enviando o post {{ post.titulo }}
{% endblock %}

{% block conteudo %}
    <h1>
        Enviar post: {{ post.titulo }} por e-mail
    </h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Enviar">
    </form>
{% endblock %}

meublog/templates/meublog/post/listarposts.html
{% extends 'meublog/base.html' %}

{% block titulo %} << Meu Blog >> {% endblock %}

{% block conteudo %}
    <h1>Meu Blog</h1>
    {% for p in posts %}
        <h2>
            <a href="{% url 'meublog:detalhe' p.publicado.year p.publicado.month p.publicado.day p.slug %}">{{ p.titulo }}</a>
        </h2>
        <p class="date">
            Publicado em {{ p.publicado }} por {{ p.autor }}
        </p>
        <p>
            {{ p.corpo|truncatewords:15|linebreaks }}
        </p>
    {% endfor %}
    {% include "paginacao.html" with page=page_obj %}
{%endblock%}